### ISSUE TITLE
"database/factories" & "database/seeds"

### ISSUE THREAD

**Issue by benoclock** [freddmn08/S07-atelier-oquiz#1]
Lorsqu'on clone et install composer sur le dépôt backend,
on obtient les erreurs :
- `Could not scan for classes inside "database/seeds" which does not appear to be a file nor a folder`
- `Could not scan for classes inside "database/factories" which does not appear to be a file nor a folder`

J'ai dû les recréer à la main pour que ça fonctionne 👎 

Il faudrait que ces répertoires restent présents dans le dépôt. Je suppose que vous les aviez supprimé.

**Comment by frdemoulin** [comment]
D'abord merci de tes reviews Ben ! On a installé Lumen dans le projet de travail en suivant le readme donné en cours (on a peut-être fait une bêtise). En tout cas, on n'a pas supprimé manuellement ces classes et je ne vois rien dans le .gitignore allant dans ce sens. Du coup, je ne sais pas trop quoi te répondre si ce n'est "je klaxonne et je passe !" :D

**Comment by frdemoulin** [comment]
Après intense réflexion, au début du projet, je me souviens avoir dû déplacé le .env qui n'était pas au bon endroit, ceci explique probablement cela ! Je plaide coupable :D
