### ISSUE TITLE
Ajax sur URL absolue spécifique à une machine

### ISSUE THREAD

**Issue by benoclock** [freddmn08/S07-atelier-oquiz#2]
https://github.com/freddmn08/S07-atelier-oquiz/blob/c10eaf8b856ee7c41e3b556e36482b522df5b3e0/frontend/public/assets/js/home.js#L12

Chez moi, je n'ai que des 404 😢

**Comment by benoclock** [comment]
L'astuce, c'est de créer, dans le `<head>`, une variable Javascript contenant l'URL jusqu'à "public" du backend.

**Comment by benoclock** [comment]
lol, je viens de voir que c'était prévu dans `app.uri`, mais pas utilisé 😂

**Comment by rachel-michel** [comment]
J'ai utilisé l'uri pour créer les liens de redirection que je met dans les href en js.
Mais comme le front et le back sont dans 2 dossiers différents, je vois pas comment utiliser l'uri pour aller dans le back :thinking: vu que l'uri pointe automatiquement vers le dossier public de mon front

**Comment by rachel-michel** [comment]
je devrais écrire un truc du style : 
'http://localhost' + app.uri + '/../../backend/public/'
ça m'a l'air étrange pour une url
