### ISSUE TITLE
Route /quiz/[id] en GET et en POST

### ISSUE THREAD

**Issue by benoclock** [freddmn08/S07-atelier-oquiz#3]
https://github.com/freddmn08/S07-atelier-oquiz/blob/45ecd58e3c7c256d4f68286ef4b4c7fe84108f0f/backend/routes/web.php#L41

Soit le commentaire est erroné
Soit la route est inutile

**Comment by frdemoulin** [comment]
Route inutile ! C'est une route que j'avais préparée en attendant la reprise du travail avec Rachel, on avait finalement abordée cette route en GET et je n'ai pas pensé à supprimer celle en POST. Oeil de lynx Ben ! Merci de tes reviews ;-)
